
print(123)
raise Exception()
print(234)

